apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skiguard

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- role.yaml
- role-binding.yaml
- service-account.yaml